type SimplePseudos =
  | ':-khtml-any-link'
  | ':-moz-any-link'
  | ':-moz-focusring'
  | ':-moz-full-screen'
  | ':-moz-placeholder'
  | ':-moz-read-only'
  | ':-moz-read-write'
  | ':-moz-ui-invalid'
  | ':-moz-ui-valid'
  | ':-ms-fullscreen'
  | ':-ms-input-placeholder'
  | ':-webkit-any-link'
  | ':-webkit-full-screen'
  | '::-moz-placeholder'
  | '::-moz-progress-bar'
  | '::-moz-range-progress'
  | '::-moz-range-thumb'
  | '::-moz-range-track'
  | '::-moz-selection'
  | '::-ms-backdrop'
  | '::-ms-browse'
  | '::-ms-check'
  | '::-ms-clear'
  | '::-ms-fill'
  | '::-ms-fill-lower'
  | '::-ms-fill-upper'
  | '::-ms-input-placeholder'
  | '::-ms-reveal'
  | '::-ms-thumb'
  | '::-ms-ticks-after'
  | '::-ms-ticks-before'
  | '::-ms-tooltip'
  | '::-ms-track'
  | '::-ms-value'
  | '::-webkit-backdrop'
  | '::-webkit-input-placeholder'
  | '::-webkit-progress-bar'
  | '::-webkit-progress-inner-value'
  | '::-webkit-progress-value'
  | '::-webkit-slider-runnable-track'
  | '::-webkit-slider-thumb'
  | '::after'
  | '::backdrop'
  | '::before'
  | '::cue'
  | '::cue-region'
  | '::first-letter'
  | '::first-line'
  | '::grammar-error'
  | '::marker'
  | '::placeholder'
  | '::selection'
  | '::spelling-error'
  | '::target-text'
  | ':active'
  | ':after'
  | ':any-link'
  | ':before'
  | ':blank'
  | ':checked'
  | ':current'
  | ':default'
  | ':defined'
  | ':disabled'
  | ':empty'
  | ':enabled'
  | ':first'
  | ':first-child'
  | ':first-letter'
  | ':first-line'
  | ':first-of-type'
  | ':focus'
  | ':focus-visible'
  | ':focus-within'
  | ':fullscreen'
  | ':future'
  | ':hover'
  | ':in-range'
  | ':indeterminate'
  | ':invalid'
  | ':last-child'
  | ':last-of-type'
  | ':left'
  | ':link'
  | ':local-link'
  | ':nth-col'
  | ':nth-last-col'
  | ':only-child'
  | ':only-of-type'
  | ':optional'
  | ':out-of-range'
  | ':past'
  | ':paused'
  | ':picture-in-picture'
  | ':placeholder-shown'
  | ':read-only'
  | ':read-write'
  | ':required'
  | ':right'
  | ':root'
  | ':scope'
  | ':target'
  | ':target-within'
  | ':user-invalid'
  | ':user-valid'
  | ':valid'
  | ':visited';

export const CSSPseudoSelectors: Record<string, SimplePseudos> = {
  cue: '::cue',
  cueRegion: '::cue-region',
  khtmlAnyLink: ':-khtml-any-link',
  mozAnyLink: ':-moz-any-link',
  mozFocusring: ':-moz-focusring',
  mozFullScreen: ':-moz-full-screen',
  mozReadOnly: ':-moz-read-only',
  mozReadWrite: ':-moz-read-write',
  mozUiInvalid: ':-moz-ui-invalid',
  mozUiValid: ':-moz-ui-valid',
  msFullscreen: ':-ms-fullscreen',
  webkitAnyLink: ':-webkit-any-link',
  webkitFullScreen: ':-webkit-full-screen',
  mozPlaceholder: '::-moz-placeholder',
  mozProgressBar: '::-moz-progress-bar',
  mozRangeProgress: '::-moz-range-progress',
  mozRangeThumb: '::-moz-range-thumb',
  mozRangeTrack: '::-moz-range-track',
  mozSelection: '::-moz-selection',
  msBackdrop: '::-ms-backdrop',
  msBrowse: '::-ms-browse',
  msCheck: '::-ms-check',
  msClear: '::-ms-clear',
  msFill: '::-ms-fill',
  msFillLower: '::-ms-fill-lower',
  msFillUpper: '::-ms-fill-upper',
  msInputPlaceholder: '::-ms-input-placeholder',
  msReveal: '::-ms-reveal',
  msThumb: '::-ms-thumb',
  msTicksAfter: '::-ms-ticks-after',
  msTicksBefore: '::-ms-ticks-before',
  msTooltip: '::-ms-tooltip',
  msTrack: '::-ms-track',
  msValue: '::-ms-value',
  webkitBackdrop: '::-webkit-backdrop',
  webkitInputPlaceholder: '::-webkit-input-placeholder',
  webkitProgressBar: '::-webkit-progress-bar',
  webkitProgressInnerValue: '::-webkit-progress-inner-value',
  webkitProgressValue: '::-webkit-progress-value',
  webkitSliderRunnableTrack: '::-webkit-slider-runnable-track',
  webkitSliderThumb: '::-webkit-slider-thumb',
  after: '::after',
  backdrop: '::backdrop',
  before: '::before',
  firstLetter: '::first-letter',
  firstLine: '::first-line',
  grammarError: '::grammar-error',
  marker: '::marker',
  placeholder: '::placeholder',
  selection: '::selection',
  spellingError: '::spelling-error',
  targetText: '::target-text',
  active: ':active',
  anyLink: ':any-link',
  blank: ':blank',
  checked: ':checked',
  current: ':current',
  default: ':default',
  defined: ':defined',
  disabled: ':disabled',
  empty: ':empty',
  enabled: ':enabled',
  first: ':first',
  firstChild: ':first-child',
  firstOfType: ':first-of-type',
  focus: ':focus',
  focusVisible: ':focus-visible',
  focusWithin: ':focus-within',
  fullscreen: ':fullscreen',
  future: ':future',
  hover: ':hover',
  inRange: ':in-range',
  indeterminate: ':indeterminate',
  invalid: ':invalid',
  lastChild: ':last-child',
  lastOfType: ':last-of-type',
  left: ':left',
  link: ':link',
  localLink: ':local-link',
  nthCol: ':nth-col',
  nthLastCol: ':nth-last-col',
  onlyChild: ':only-child',
  onlyOfType: ':only-of-type',
  optional: ':optional',
  outOfRange: ':out-of-range',
  past: ':past',
  paused: ':paused',
  pictureInPicture: ':picture-in-picture',
  placeholderShown: ':placeholder-shown',
  readOnly: ':read-only',
  readWrite: ':read-write',
  required: ':required',
  right: ':right',
  root: ':root',
  scope: ':scope',
  target: ':target',
  targetWithin: ':target-within',
  userInvalid: ':user-invalid',
  userValid: ':user-valid',
  valid: ':valid',
  visited: ':visited',
};
