import Head from 'next/head';
import Image from 'next/image';
import { FC, PropsWithChildren } from 'react';

import { Anchor, Box, Typography } from '@/elements';

const DescriptionText: FC<PropsWithChildren> = ({ children }) => (
  <Typography
    m="0"
    p="XL"
    borderRadius="L"
    border="1px solid"
    position="relative"
  >
    {children}
  </Typography>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        as="main"
        display="flex"
        padding="6rem"
        minHeight="100vh"
        alignItems="center"
        flexDirection="column"
        justifyContent="space-between"
      >
        <Box
          zIndex={2}
          width="100%"
          display="inherit"
          maxWidth="1100px"
          fontSize="0.85rem"
          alignItems="inherit"
          justifyContent="inherit"
          fontFamily="ui-monospace, Menlo, Monaco, 'Cascadia Mono', 'Segoe UI Mono', 'Roboto Mono', 'Oxygen Mono', 'Ubuntu Monospace', 'Source Code Pro', 'Fira Mono', 'Droid Sans Mono', 'Courier New', monospace"
        >
          <DescriptionText>
            Get started by editing&nbsp;
            <Typography
              as="code"
              fontWeight="700"
              fontFamily="ui-monospace, Menlo, Monaco, 'Cascadia Mono', 'Segoe UI Mono', 'Roboto Mono', 'Oxygen Mono', 'Ubuntu Monospace', 'Source Code Pro', 'Fira Mono', 'Droid Sans Mono', 'Courier New', monospace"
            >
              pages/index.tsx
            </Typography>
          </DescriptionText>
          <Box>
            <Anchor
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              rel="noopener noreferrer"
              target="_blank"
            >
              By{' '}
              <Box as="span" filter="invert(1)">
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={100}
                  height={24}
                  priority
                />
              </Box>
            </Anchor>
          </Box>
        </Box>
      </Box>
    </>
  );
}
