import { ThemeValuesMap } from '@stylin.js/core';

export const THEMED_VALUES_MAP: ThemeValuesMap = {
  gap: 'space',
  rowGap: 'space',
  columnGap: 'space',
  margin: 'space',
  marginTop: 'space',
  marginRight: 'space',
  marginBottom: 'space',
  marginLeft: 'space',
  padding: 'space',
  paddingTop: 'space',
  paddingRight: 'space',
  paddingBottom: 'space',
  paddingLeft: 'space',
  fontSize: 'fontSizes',
  color: 'colors',
  borderColor: 'colors',
  borderTopColor: 'colors',
  borderLeftColor: 'colors',
  borderBlockColor: 'colors',
  borderRightColor: 'colors',
  borderBottomColor: 'colors',
  borderInlineColor: 'colors',
  borderBlockEndColor: 'colors',
  borderInlineEndColor: 'colors',
  borderBlockStartColor: 'colors',
  borderInlineStartColor: 'colors',
  background: 'colors',
  backgroundColor: 'colors',
  borderRadius: 'radii',
  borderEndEndRadius: 'radii',
  borderTopLeftRadius: 'radii',
  borderTopRightRadius: 'radii',
  borderEndStartRadius: 'radii',
  borderStartEndRadius: 'radii',
  borderBottomLeftRadius: 'radii',
  borderStartStartRadius: 'radii',
  borderBottomRightRadius: 'radii',
};
